-- Stage 4 Diagnostics
-- Scope: CY2011 -> CY2012, CurrencyKey = 100

-- 1. Product Category
DROP TABLE IF EXISTS fact_growth_quality_category CASCADE;
CREATE TABLE fact_growth_quality_category AS
SELECT "Category", "r11" AS cy2011_net_revenue, "r12" AS cy2012_net_revenue, "revenue_change", CASE WHEN "r11" > 0 THEN ("revenue_change" / "r11") * 100 ELSE NULL END AS revenue_growth_pct, "gp11" AS cy2011_gross_profit, "gp12" AS cy2012_gross_profit, "gp_change" AS gross_profit_change, CASE WHEN "gp11" <> 0 THEN ("gp_change" / ABS("gp11")) * 100 ELSE NULL END AS gross_profit_growth_pct, "gm11_pct" AS cy2011_gross_margin_pct, "gm12_pct" AS cy2012_gross_margin_pct, "gm_pct_change" AS gross_margin_change_ppt, "price_effect", "unit_cost_effect", "volume_effect", "mix_effect", CASE WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" >= 0 THEN 'Tier 1 - High-quality growth' WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" < 0 THEN 'Tier 2 - Margin-dilutive growth' WHEN "revenue_change" > 0 AND "gp_change" < 0 AND "gm_pct_change" < 0 THEN 'Tier 3 - Value-destructive growth' WHEN "revenue_change" < 0 AND "gp_change" < 0 THEN 'Tier 4 - Contraction' WHEN "revenue_change" < 0 AND "gp_change" > 0 AND "gm_pct_change" > 0 THEN 'Tier 5 - Profitable Contraction / Portfolio Improvement' ELSE 'Other Special Case' END AS growth_quality_tier FROM rollup_profitability_category ORDER BY "gp_change" DESC;

-- 2. Product Subcategory
DROP TABLE IF EXISTS fact_growth_quality_subcategory CASCADE;
CREATE TABLE fact_growth_quality_subcategory AS
SELECT "Category", "Subcategory", "r11" AS cy2011_net_revenue, "r12" AS cy2012_net_revenue, "revenue_change", CASE WHEN "r11" > 0 THEN ("revenue_change" / "r11") * 100 ELSE NULL END AS revenue_growth_pct, "gp11" AS cy2011_gross_profit, "gp12" AS cy2012_gross_profit, "gp_change" AS gross_profit_change, CASE WHEN "gp11" <> 0 THEN ("gp_change" / ABS("gp11")) * 100 ELSE NULL END AS gross_profit_growth_pct, "gm11_pct" AS cy2011_gross_margin_pct, "gm12_pct" AS cy2012_gross_margin_pct, "gm_pct_change" AS gross_margin_change_ppt, "price_effect", "unit_cost_effect", "volume_effect", "mix_effect", CASE WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" >= 0 THEN 'Tier 1 - High-quality growth' WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" < 0 THEN 'Tier 2 - Margin-dilutive growth' WHEN "revenue_change" > 0 AND "gp_change" < 0 AND "gm_pct_change" < 0 THEN 'Tier 3 - Value-destructive growth' WHEN "revenue_change" < 0 AND "gp_change" < 0 THEN 'Tier 4 - Contraction' WHEN "revenue_change" < 0 AND "gp_change" > 0 AND "gm_pct_change" > 0 THEN 'Tier 5 - Profitable Contraction / Portfolio Improvement' WHEN "r11" = 0 AND "r12" > 0 AND "gp12" > 0 THEN 'Tier 1 - High-quality growth (New Segment Entry)' WHEN "r11" = 0 AND "r12" > 0 AND "gp12" <= 0 THEN 'Tier 3 - Value-destructive growth (New Segment Entry)' ELSE 'Other Special Case' END AS growth_quality_tier FROM rollup_profitability_subcategory ORDER BY "gp_change" DESC;

-- 3. ProductKey
DROP TABLE IF EXISTS fact_growth_quality_product CASCADE;
CREATE TABLE fact_growth_quality_product AS
SELECT "ProductKey", "ProductName", "Category", "Subcategory", "product_status", "r11" AS cy2011_net_revenue, "r12" AS cy2012_net_revenue, "revenue_change", CASE WHEN "r11" > 0 THEN ("revenue_change" / "r11") * 100 ELSE NULL END AS revenue_growth_pct, "gp11" AS cy2011_gross_profit, "gp12" AS cy2012_gross_profit, "gp_change" AS gross_profit_change, CASE WHEN "gp11" <> 0 THEN ("gp_change" / ABS("gp11")) * 100 ELSE NULL END AS gross_profit_growth_pct, "gm11_pct" AS cy2011_gross_margin_pct, "gm12_pct" AS cy2012_gross_margin_pct, "gm_pct_change" AS gross_margin_change_ppt, "price_effect", "unit_cost_effect", "volume_effect", "mix_effect", CASE WHEN "product_status" = 'NEW_PRODUCT' AND "gp12" > 0 THEN 'Tier 1 - High-quality growth (New Product)' WHEN "product_status" = 'NEW_PRODUCT' AND "gp12" <= 0 THEN 'Tier 3 - Value-destructive growth (New Product)' WHEN "product_status" = 'DISCONTINUED_PRODUCT' AND "gp11" > 0 THEN 'Tier 4 - Contraction (Discontinued Product)' WHEN "product_status" = 'DISCONTINUED_PRODUCT' AND "gp11" <= 0 THEN 'Tier 5 - Profitable Contraction (Discontinued Product)' WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" >= 0 THEN 'Tier 1 - High-quality growth' WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" < 0 THEN 'Tier 2 - Margin-dilutive growth' WHEN "revenue_change" > 0 AND "gp_change" < 0 AND "gm_pct_change" < 0 THEN 'Tier 3 - Value-destructive growth' WHEN "revenue_change" < 0 AND "gp_change" < 0 THEN 'Tier 4 - Contraction' WHEN "revenue_change" < 0 AND "gp_change" > 0 AND "gm_pct_change" > 0 THEN 'Tier 5 - Profitable Contraction / Portfolio Improvement' ELSE 'Other Special Case' END AS growth_quality_tier FROM fact_profitability_decomposition_product ORDER BY "gp_change" DESC;

-- 4. Business Type
DROP TABLE IF EXISTS fact_growth_quality_business_type CASCADE;
CREATE TABLE fact_growth_quality_business_type AS
SELECT "BusinessType", "r11" AS cy2011_net_revenue, "r12" AS cy2012_net_revenue, "revenue_change", CASE WHEN "r11" > 0 THEN ("revenue_change" / "r11") * 100 ELSE NULL END AS revenue_growth_pct, "gp11" AS cy2011_gross_profit, "gp12" AS cy2012_gross_profit, "gp_change" AS gross_profit_change, CASE WHEN "gp11" <> 0 THEN ("gp_change" / ABS("gp11")) * 100 ELSE NULL END AS gross_profit_growth_pct, "gm11_pct" AS cy2011_gross_margin_pct, "gm12_pct" AS cy2012_gross_margin_pct, "gm_pct_change" AS gross_margin_change_ppt, "price_effect", "unit_cost_effect", "volume_effect", "mix_effect", CASE WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" >= 0 THEN 'Tier 1 - High-quality growth' WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" < 0 THEN 'Tier 2 - Margin-dilutive growth' WHEN "revenue_change" > 0 AND "gp_change" < 0 AND "gm_pct_change" < 0 THEN 'Tier 3 - Value-destructive growth' WHEN "revenue_change" < 0 AND "gp_change" < 0 THEN 'Tier 4 - Contraction' WHEN "revenue_change" < 0 AND "gp_change" > 0 AND "gm_pct_change" > 0 THEN 'Tier 5 - Profitable Contraction / Portfolio Improvement' ELSE 'Other Special Case' END AS growth_quality_tier FROM rollup_profitability_business_type ORDER BY "gp_change" DESC;

-- 5. Country
DROP TABLE IF EXISTS fact_growth_quality_country CASCADE;
CREATE TABLE fact_growth_quality_country AS
SELECT "Country", "r11" AS cy2011_net_revenue, "r12" AS cy2012_net_revenue, "revenue_change", CASE WHEN "r11" > 0 THEN ("revenue_change" / "r11") * 100 ELSE NULL END AS revenue_growth_pct, "gp11" AS cy2011_gross_profit, "gp12" AS cy2012_gross_profit, "gp_change" AS gross_profit_change, CASE WHEN "gp11" <> 0 THEN ("gp_change" / ABS("gp11")) * 100 ELSE NULL END AS gross_profit_growth_pct, "gm11_pct" AS cy2011_gross_margin_pct, "gm12_pct" AS cy2012_gross_margin_pct, "gm_pct_change" AS gross_margin_change_ppt, "price_effect", "unit_cost_effect", "volume_effect", "mix_effect", CASE WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" >= 0 THEN 'Tier 1 - High-quality growth' WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" < 0 THEN 'Tier 2 - Margin-dilutive growth' WHEN "revenue_change" > 0 AND "gp_change" < 0 AND "gm_pct_change" < 0 THEN 'Tier 3 - Value-destructive growth' WHEN "revenue_change" < 0 AND "gp_change" < 0 THEN 'Tier 4 - Contraction' WHEN "revenue_change" < 0 AND "gp_change" > 0 AND "gm_pct_change" > 0 THEN 'Tier 5 - Profitable Contraction / Portfolio Improvement' ELSE 'Other Special Case' END AS growth_quality_tier FROM rollup_profitability_country ORDER BY "gp_change" DESC;

-- 6. Territory Region
DROP TABLE IF EXISTS fact_growth_quality_territory_region CASCADE;
CREATE TABLE fact_growth_quality_territory_region AS
SELECT "Country", "TerritoryRegion", "r11" AS cy2011_net_revenue, "r12" AS cy2012_net_revenue, "revenue_change", CASE WHEN "r11" > 0 THEN ("revenue_change" / "r11") * 100 ELSE NULL END AS revenue_growth_pct, "gp11" AS cy2011_gross_profit, "gp12" AS cy2012_gross_profit, "gp_change" AS gross_profit_change, CASE WHEN "gp11" <> 0 THEN ("gp_change" / ABS("gp11")) * 100 ELSE NULL END AS gross_profit_growth_pct, "gm11_pct" AS cy2011_gross_margin_pct, "gm12_pct" AS cy2012_gross_margin_pct, "gm_pct_change" AS gross_margin_change_ppt, "price_effect", "unit_cost_effect", "volume_effect", "mix_effect", CASE WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" >= 0 THEN 'Tier 1 - High-quality growth' WHEN "revenue_change" > 0 AND "gp_change" > 0 AND "gm_pct_change" < 0 THEN 'Tier 2 - Margin-dilutive growth' WHEN "revenue_change" > 0 AND "gp_change" < 0 AND "gm_pct_change" < 0 THEN 'Tier 3 - Value-destructive growth' WHEN "revenue_change" < 0 AND "gp_change" < 0 THEN 'Tier 4 - Contraction' WHEN "revenue_change" < 0 AND "gp_change" > 0 AND "gm_pct_change" > 0 THEN 'Tier 5 - Profitable Contraction / Portfolio Improvement' ELSE 'Other Special Case' END AS growth_quality_tier FROM rollup_profitability_territory_region ORDER BY "gp_change" DESC;

-- 7. Top GP Contributors & Drags
DROP TABLE IF EXISTS fact_top_gp_contributors CASCADE;
CREATE TABLE fact_top_gp_contributors AS SELECT 'Product' AS level_type, "ProductKey"::text AS item_id, "ProductName" AS item_name, "Category", "Subcategory", gross_profit_change, revenue_change, gross_margin_change_ppt, growth_quality_tier FROM fact_growth_quality_product ORDER BY gross_profit_change DESC LIMIT 10;
DROP TABLE IF EXISTS fact_top_gp_drags CASCADE;
CREATE TABLE fact_top_gp_drags AS SELECT 'Product' AS level_type, "ProductKey"::text AS item_id, "ProductName" AS item_name, "Category", "Subcategory", gross_profit_change, revenue_change, gross_margin_change_ppt, growth_quality_tier FROM fact_growth_quality_product ORDER BY gross_profit_change ASC LIMIT 10;

-- 8. Discount Diagnostic Table
DROP TABLE IF EXISTS fact_discount_diagnostic CASCADE;
CREATE TABLE fact_discount_diagnostic AS WITH agg AS (SELECT 'Portfolio' AS level_name, 'Portfolio' AS segment_name, "CalendarYear", SUM("OrderQuantity") AS units, SUM("ExtendedAmount") AS gross_revenue, SUM("DiscountAmount") AS discount_amount, SUM("SalesAmount") AS net_revenue, SUM("DiscountAmount") / NULLIF(SUM("ExtendedAmount"), 0) * 100 AS discount_rate_pct, SUM("ExtendedAmount") / NULLIF(SUM("OrderQuantity"), 0) AS list_asp, SUM("SalesAmount") / NULLIF(SUM("OrderQuantity"), 0) AS net_asp FROM abt_reseller_sales WHERE "CurrencyKey" = 100 GROUP BY "CalendarYear" UNION ALL SELECT 'Category' AS level_name, "Category" AS segment_name, "CalendarYear", SUM("OrderQuantity") AS units, SUM("ExtendedAmount") AS gross_revenue, SUM("DiscountAmount") AS discount_amount, SUM("SalesAmount") AS net_revenue, SUM("DiscountAmount") / NULLIF(SUM("ExtendedAmount"), 0) * 100 AS discount_rate_pct, SUM("ExtendedAmount") / NULLIF(SUM("OrderQuantity"), 0) AS list_asp, SUM("SalesAmount") / NULLIF(SUM("OrderQuantity"), 0) AS net_asp FROM abt_reseller_sales WHERE "CurrencyKey" = 100 GROUP BY "Category", "CalendarYear" UNION ALL SELECT 'BusinessType' AS level_name, "BusinessType" AS segment_name, "CalendarYear", SUM("OrderQuantity") AS units, SUM("ExtendedAmount") AS gross_revenue, SUM("DiscountAmount") AS discount_amount, SUM("SalesAmount") AS net_revenue, SUM("DiscountAmount") / NULLIF(SUM("ExtendedAmount"), 0) * 100 AS discount_rate_pct, SUM("ExtendedAmount") / NULLIF(SUM("OrderQuantity"), 0) AS list_asp, SUM("SalesAmount") / NULLIF(SUM("OrderQuantity"), 0) AS net_asp FROM abt_reseller_sales WHERE "CurrencyKey" = 100 GROUP BY "BusinessType", "CalendarYear"), y11 AS (SELECT * FROM agg WHERE "CalendarYear" = 2011), y12 AS (SELECT * FROM agg WHERE "CalendarYear" = 2012) SELECT y11.level_name, y11.segment_name, y11.units AS units_2011, y12.units AS units_2012, y12.units - y11.units AS units_change, y11.gross_revenue AS gross_revenue_2011, y12.gross_revenue AS gross_revenue_2012, y12.gross_revenue - y11.gross_revenue AS gross_revenue_change, y11.discount_amount AS discount_amount_2011, y12.discount_amount AS discount_amount_2012, y12.discount_amount - y11.discount_amount AS discount_amount_change, y11.net_revenue AS net_revenue_2011, y12.net_revenue AS net_revenue_2012, y12.net_revenue - y11.net_revenue AS net_revenue_change, y11.discount_rate_pct AS discount_rate_pct_2011, y12.discount_rate_pct AS discount_rate_pct_2012, y12.discount_rate_pct - y11.discount_rate_pct AS discount_rate_change_ppt, y11.list_asp AS list_asp_2011, y12.list_asp AS list_asp_2012, y12.list_asp - y11.list_asp AS list_asp_change, y11.net_asp AS net_asp_2011, y12.net_asp AS net_asp_2012, y12.net_asp - y11.net_asp AS net_asp_change FROM y11 JOIN y12 ON y11.level_name = y12.level_name AND y11.segment_name = y12.segment_name ORDER BY y11.level_name, y11.segment_name;